# Artificial Neural Network(ANN)

### Data Preprocessing

In [1]:
# Importing the libraries
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline
plt.rcParams['figure.figsize'] = [14, 8]

In [2]:
# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')

In [3]:
dataset.head(1)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   

   Tenure  Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  \
0       2      0.0              1          1               1        101348.88   

   Exited  
0       1

In [4]:
X = dataset.iloc[:, [3, 4, 6, 7, 8, 9, 10, 11, 12]].values

In [5]:
y = dataset.iloc[:, 13].values

In [6]:
X[0]

array([619, 'France', 42, 2, 0.0, 1, 1, 1, 101348.88], dtype=object)

In [7]:
y[0]

1

In [8]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
X[:, 1] = labelencoder_X.fit_transform(X[:, 1])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]

In [9]:
X[0:2]

array([[  0.00000000e+00,   0.00000000e+00,   6.19000000e+02,
          4.20000000e+01,   2.00000000e+00,   0.00000000e+00,
          1.00000000e+00,   1.00000000e+00,   1.00000000e+00,
          1.01348880e+05],
       [  0.00000000e+00,   1.00000000e+00,   6.08000000e+02,
          4.10000000e+01,   1.00000000e+00,   8.38078600e+04,
          1.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          1.12542580e+05]])

In [10]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [11]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
X_train[0:2]

array([[-0.5698444 ,  1.74309049,  0.16958176, -0.46460796,  0.00666099,
        -1.21571749,  0.8095029 ,  0.64259497, -1.03227043,  1.10643166],
       [ 1.75486502, -0.57369368, -2.30455945,  0.30102557, -1.37744033,
        -0.00631193, -0.92159124,  0.64259497,  0.9687384 , -0.74866447]])

In [13]:
# Importing the Keras libraries and packages
import keras

Using TensorFlow backend.
/home/baka/Programs/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


In [14]:
from keras.models import Sequential
from keras.layers import Dense

In [15]:
# Initialization of ANN
classifier = Sequential()

In [16]:
dir(keras.activations)

['K',
 'Layer',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'absolute_import',
 'deserialize',
 'deserialize_keras_object',
 'elu',
 'get',
 'hard_sigmoid',
 'linear',
 'relu',
 'selu',
 'serialize',
 'sigmoid',
 'six',
 'softmax',
 'softplus',
 'softsign',
 'tanh',
 'warnings']

In [17]:
# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 10))

In [18]:
# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

In [19]:
# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid', input_dim = 10))

In [20]:
dir(keras.optimizers)

['Adadelta',
 'Adagrad',
 'Adam',
 'Adamax',
 'K',
 'Nadam',
 'Optimizer',
 'RMSprop',
 'SGD',
 'TFOptimizer',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'absolute_import',
 'adadelta',
 'adagrad',
 'adam',
 'adamax',
 'clip_norm',
 'copy',
 'deserialize',
 'deserialize_keras_object',
 'get',
 'interfaces',
 'nadam',
 'rmsprop',
 'serialize',
 'serialize_keras_object',
 'sgd',
 'six',
 'tf',
 'zip']

In [21]:
dir(keras.losses)

['K',
 'KLD',
 'MAE',
 'MAPE',
 'MSE',
 'MSLE',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'absolute_import',
 'binary_crossentropy',
 'categorical_crossentropy',
 'categorical_hinge',
 'cosine',
 'cosine_proximity',
 'deserialize',
 'deserialize_keras_object',
 'get',
 'hinge',
 'kld',
 'kullback_leibler_divergence',
 'logcosh',
 'mae',
 'mape',
 'mean_absolute_error',
 'mean_absolute_percentage_error',
 'mean_squared_error',
 'mean_squared_logarithmic_error',
 'mse',
 'msle',
 'poisson',
 'serialize',
 'six',
 'sparse_categorical_crossentropy',
 'squared_hinge']

In [22]:
# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [23]:
# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 30)

Epoch 1/30
8000/8000 [==============================] - 2s 246us/step - loss: 0.4871 - acc: 0.7952
Epoch 2/30
8000/8000 [==============================] - 2s 241us/step - loss: 0.4214 - acc: 0.7960
Epoch 3/30
8000/8000 [==============================] - 2s 236us/step - loss: 0.4107 - acc: 0.8054
Epoch 4/30
8000/8000 [==============================] - 2s 243us/step - loss: 0.4013 - acc: 0.8277
Epoch 5/30
8000/8000 [==============================] - 2s 243us/step - loss: 0.3935 - acc: 0.8284
Epoch 6/30
8000/8000 [==============================] - 2s 242us/step - loss: 0.3884 - acc: 0.8296
Epoch 7/30
8000/8000 [==============================] - 2s 255us/step - loss: 0.3845 - acc: 0.8339
Epoch 8/30
8000/8000 [==============================] - 2s 285us/step - loss: 0.3809 - acc: 0.8430
Epoch 9/30
8000/8000 [==============================] - 2s 245us/step - loss: 0.3771 - acc: 0.8449
Epoch 10/30
8000/8000 [==============================] - 2s 241us/step - loss: 0.3733 - acc: 0.8485
Epoch 11/

In [24]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5) 

In [25]:
y_pred[0:10]

array([[False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True]], dtype=bool)

In [26]:
y_test[0:10]

array([0, 1, 0, 0, 0, 1, 0, 0, 1, 1])

In [27]:
# Making the confussion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1516,   79],
       [ 212,  193]])

In [29]:
# Accuracy
(1516+193)/2000

0.8545